# Generated by Django 6.0.5 on 2026-05-11 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('nivel_tea', models.CharField(choices=[('1', 'Nivel 1 - Necesita apoyo'), ('2', 'Nivel 2 - Necesita apoyo sustancial'), ('3', 'Nivel 3 - Necesita apoyo muy sustancial')], max_length=20, verbose_name='Nivel TEA')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la regla')),
                ('campo_condicion', models.CharField(help_text='Nombre exacto del campo del modelo Evaluacion (ej: dificultad_comunicacion)', max_length=100, verbose_name='Campo a evaluar')),
                ('operador', models.CharField(choices=[('==', 'Igual a'), ('!=', 'Distinto de'), ('>', 'Mayor que'), ('<', 'Menor que')], default='==', max_length=5, verbose_name='Operador de comparación')),
                ('valor_condicion', models.CharField(help_text='Valor con el que se compara (ej: alto, True, False)', max_length=100, verbose_name='Valor esperado')),
                ('accion', models.TextField(verbose_name='Recomendación pedagógica (acción)')),
                ('categoria', models.CharField(choices=[('comunicacion', 'Comunicación'), ('conducta', 'Conducta'), ('social', 'Interacción Social'), ('general', 'General')], default='general', max_length=50, verbose_name='Categoría')),
                ('prioridad', models.PositiveIntegerField(default=1, help_text='Mayor número = mayor prioridad en la presentación', verbose_name='Prioridad')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Regla activa?')),
            ],
            options={
                'verbose_name': 'Regla',
                'verbose_name_plural': 'Reglas',
                'ordering': ['-prioridad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('especialidad', models.CharField(blank=True, max_length=100, verbose_name='Especialidad')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad_comunicacion', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10, verbose_name='Dificultad de comunicación')),
                ('usa_lenguaje_verbal', models.BooleanField(default=True, verbose_name='¿Usa lenguaje verbal?')),
                ('conductas_repetitivas', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10, verbose_name='Conductas repetitivas')),
                ('reacciones_sensoriales', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10, verbose_name='Reacciones sensoriales intensas')),
                ('crisis_frecuentes', models.BooleanField(default=False, verbose_name='¿Presenta crisis frecuentes?')),
                ('interaccion_social', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10, verbose_name='Nivel de interacción social')),
                ('interes_pares', models.BooleanField(default=False, verbose_name='¿Muestra interés por sus pares?')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de evaluación')),
                ('notas_adicionales', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='experto.estudiante', verbose_name='Estudiante evaluado')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_realizadas', to='experto.instructor', verbose_name='Instructor que evalúa')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='experto.instructor', verbose_name='Instructor responsable'),
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto de la recomendación')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='experto.evaluacion', verbose_name='Evaluación origen')),
                ('regla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones_generadas', to='experto.regla', verbose_name='Regla que la generó')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
