# Generated by Django 6.0.5 on 2026-05-17 21:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('edad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Edad')),
                ('foto_carnet', models.ImageField(blank=True, null=True, upload_to='fotos_estudiantes/', verbose_name='Foto carnet')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la regla')),
                ('condicion', models.TextField(help_text='Descripción legible de la condición que activa esta regla.', verbose_name='Condición (SI...)')),
                ('recomendacion', models.TextField(verbose_name='Recomendación pedagógica (ENTONCES...)')),
                ('recursos_didacticos', models.TextField(blank=True, verbose_name='Recursos didácticos sugeridos')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Regla activa?')),
            ],
            options={
                'verbose_name': 'Regla',
                'verbose_name_plural': 'Reglas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDSM5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('nivel_comunicacion_social', models.CharField(choices=[('necesita_apoyo', 'Nivel 1 — Necesita apoyo'), ('apoyo_sustancial', 'Nivel 2 — Apoyo sustancial'), ('apoyo_constante', 'Nivel 3 — Necesita apoyo constante')], max_length=30, verbose_name='Nivel de comunicación social (Criterio A)')),
                ('obs_reciprocidad', models.TextField(blank=True, verbose_name='A.1 — Reciprocidad socioemocional (observaciones)')),
                ('obs_comunicacion_no_verbal', models.TextField(blank=True, verbose_name='A.2 — Comunicación no verbal (observaciones)')),
                ('obs_desarrollo_relaciones', models.TextField(blank=True, verbose_name='A.3 — Desarrollo y comprensión de relaciones (observaciones)')),
                ('nivel_conductas_repetitivas', models.CharField(choices=[('necesita_ayuda', 'Nivel 1 — Necesita ayuda'), ('ayuda_notable', 'Nivel 2 — Necesita ayuda notable'), ('ayuda_muy_notable', 'Nivel 3 — Necesita ayuda muy notable')], max_length=30, verbose_name='Nivel de conductas repetitivas (Criterio B)')),
                ('movimientos_repetitivos', models.BooleanField(default=False, verbose_name='B.1 — Movimientos, uso de objetos o habla estereotipada')),
                ('inflexibilidad_rutinas', models.BooleanField(default=False, verbose_name='B.2 — Insistencia en la monotonía / inflexibilidad de rutinas')),
                ('intereses_restringidos', models.BooleanField(default=False, verbose_name='B.3 — Intereses muy restringidos y fijos')),
                ('alteraciones_sensoriales', models.BooleanField(default=False, verbose_name='B.4 — Hiper o hiporreactividad sensorial')),
                ('inicio_temprano', models.BooleanField(default=False, verbose_name='C — Síntomas presentes en las primeras fases del desarrollo')),
                ('deterioro_significativo', models.BooleanField(default=False, verbose_name='D — Causa deterioro clínicamente significativo')),
                ('no_explicado_otra_condicion', models.BooleanField(default=False, verbose_name='E — No se explica mejor por discapacidad intelectual aislada')),
                ('discapacidad_intelectual', models.BooleanField(default=False, verbose_name='Con discapacidad intelectual acompañante')),
                ('deterioro_lenguaje', models.BooleanField(default=False, verbose_name='Con deterioro del lenguaje acompañante')),
                ('condicion_medica_asociada', models.CharField(blank=True, max_length=200, verbose_name='Afección médica o genética asociada (opcional)')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_dsm5', to='experto.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Evaluación DSM-5',
                'verbose_name_plural': 'Evaluaciones DSM-5',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionPedagogica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('nivel_comunicacion_social', models.CharField(choices=[('necesita_apoyo', 'Nivel 1 — Necesita apoyo'), ('apoyo_sustancial', 'Nivel 2 — Apoyo sustancial'), ('apoyo_constante', 'Nivel 3 — Necesita apoyo constante')], max_length=30, verbose_name='Nivel — Área comunicación social')),
                ('observaciones_comunicacion', models.TextField(blank=True, verbose_name='Observaciones — Comunicación social')),
                ('nivel_conductas_repetitivas', models.CharField(choices=[('necesita_ayuda', 'Nivel 1 — Necesita ayuda'), ('ayuda_notable', 'Nivel 2 — Necesita ayuda notable'), ('ayuda_muy_notable', 'Nivel 3 — Necesita ayuda muy notable')], max_length=30, verbose_name='Nivel — Área conductas repetitivas')),
                ('observaciones_conductas', models.TextField(blank=True, verbose_name='Observaciones — Conductas repetitivas')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_pedagogicas', to='experto.estudiante', verbose_name='Estudiante')),
                ('evaluacion_dsm5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_pedagogicas', to='experto.evaluaciondsm5', verbose_name='Evaluación DSM-5 asociada')),
            ],
            options={
                'verbose_name': 'Evaluación Pedagógica',
                'verbose_name_plural': 'Evaluaciones Pedagógicas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='experto.instructor', verbose_name='Instructor responsable'),
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto de la recomendación')),
                ('generada_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('evaluacion_pedagogica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='experto.evaluacionpedagogica', verbose_name='Evaluación pedagógica origen')),
                ('regla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones_generadas', to='experto.regla', verbose_name='Regla que la generó')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
                'ordering': ['generada_en'],
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('edad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Edad')),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('union_libre', 'Unión libre')], max_length=20, verbose_name='Estado civil')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('foto_carnet', models.ImageField(blank=True, null=True, upload_to='fotos_representantes/', verbose_name='Foto carnet')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representante', to='experto.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
            },
        ),
    ]
