# Generated by Django 6.0.5 on 2026-05-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
