# Generated by Django 4.2.30 on 2026-05-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experto', '0002_representante_telefono_alter_representante_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='cedula',
            field=models.CharField(default='00000000000', max_length=15, unique=True, verbose_name='Cédula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='representante',
            name='parentesco',
            field=models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('tutor', 'Tutor/a'), ('abuelo', 'Abuelo/a'), ('otro', 'Otro')], default='otro', max_length=10, verbose_name='Parentesco con el estudiante'),
            preserve_default=False,
        ),
    ]
