# Generated by Django 4.2.30 on 2026-05-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experto', '0003_add_cedula_parentesco_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código de recuperación'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='reset_code_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiración del código'),
        ),
    ]
