# Generated by Django 6.0.5 on 2026-05-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experto', '0003_add_cedula_parentesco_representante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciondsm5',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='evaluacionpedagogica',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
