# Generated by Django 4.2.30 on 2026-05-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experto', '0004_add_reset_code_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_instructores/', verbose_name='Foto de perfil'),
        ),
    ]
