# Generated by Django 4.2.30 on 2026-05-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experto', '0005_add_foto_perfil_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='representante',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='direccion',
            field=models.TextField(verbose_name='Dirección detallada'),
        ),
    ]
