# Generated by Django 6.0.5 on 2026-05-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experto', '0004_alter_evaluaciondsm5_fecha_and_more'),
        ('experto', '0005_add_foto_perfil_instructor'),
    ]

    operations = [
    ]
