# Generated by Django 4.2.30 on 2026-05-18 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experto', '0006_add_estado_municipio_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Cédula'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección detallada'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('union_libre', 'Unión libre')], max_length=20, null=True, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
