# Generated by Django 6.0.5 on 2026-05-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experto', '0006_merge_20260518_1123'),
        ('experto', '0007_unify_instructor_fields'),
    ]

    operations = [
    ]
