# Generated by Django 6.0.5 on 2026-05-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experto', '0008_merge_20260518_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='respuesta_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Respuesta a pregunta 1: Mascota'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='respuesta_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Respuesta a pregunta 2: Ciudad natal'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='respuesta_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Respuesta a pregunta 3: Comida favorita'),
        ),
    ]
