# Generated by Django 4.2.30 on 2026-05-20 22:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experto', '0009_instructor_respuesta_1_instructor_respuesta_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la evaluación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la evaluación')),
                ('tipo', models.CharField(choices=[('TEA', 'TEA'), ('TDAH', 'TDAH'), ('LENGUAJE', 'Lenguaje'), ('CONDUCTA', 'Conducta'), ('SENSORIAL', 'Sensorial'), ('OTRO', 'Otro')], default='TEA', max_length=20, verbose_name='Tipo de evaluación')),
                ('puntaje_obtenido', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Puntaje obtenido')),
                ('puntaje_maximo', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Puntaje máximo')),
                ('porcentaje', models.FloatField(default=0.0, editable=False, verbose_name='Porcentaje (%)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_evolucion', to='experto.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Evaluación de Evolución',
                'verbose_name_plural': 'Evaluaciones de Evolución',
                'ordering': ['fecha'],
            },
        ),
    ]
