# Generated by Django 4.2.30 on 2026-05-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experto', '0010_estudiante_fecha_nacimiento_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='tema',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='dark', max_length=10, verbose_name='Tema del sistema'),
        ),
    ]
