# Generated by Django 4.2.30 on 2026-05-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experto', '0011_instructor_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluaciondsm5',
            name='obs_comunicacion_no_verbal',
        ),
        migrations.RemoveField(
            model_name='evaluaciondsm5',
            name='obs_desarrollo_relaciones',
        ),
        migrations.RemoveField(
            model_name='evaluaciondsm5',
            name='obs_reciprocidad',
        ),
        migrations.AddField(
            model_name='evaluaciondsm5',
            name='a1_observaciones',
            field=models.TextField(blank=True, verbose_name='A.1 — Observaciones'),
        ),
        migrations.AddField(
            model_name='evaluaciondsm5',
            name='a1_reciprocidad',
            field=models.CharField(choices=[('ausente', 'Ausente / No aplica'), ('leve', 'Leve (requiere apoyo)'), ('moderado', 'Moderado (requiere apoyo sustancial)'), ('grave', 'Grave (requiere apoyo muy sustancial)')], default='ausente', max_length=20, verbose_name='A.1 — Deficiencias en la reciprocidad socioemocional'),
        ),
        migrations.AddField(
            model_name='evaluaciondsm5',
            name='a2_comunicacion_no_verbal',
            field=models.CharField(choices=[('ausente', 'Ausente / No aplica'), ('leve', 'Leve (requiere apoyo)'), ('moderado', 'Moderado (requiere apoyo sustancial)'), ('grave', 'Grave (requiere apoyo muy sustancial)')], default='ausente', max_length=20, verbose_name='A.2 — Deficiencias en conductas comunicativas no verbales'),
        ),
        migrations.AddField(
            model_name='evaluaciondsm5',
            name='a2_observaciones',
            field=models.TextField(blank=True, verbose_name='A.2 — Observaciones'),
        ),
        migrations.AddField(
            model_name='evaluaciondsm5',
            name='a3_observaciones',
            field=models.TextField(blank=True, verbose_name='A.3 — Observaciones'),
        ),
        migrations.AddField(
            model_name='evaluaciondsm5',
            name='a3_relaciones',
            field=models.CharField(choices=[('ausente', 'Ausente / No aplica'), ('leve', 'Leve (requiere apoyo)'), ('moderado', 'Moderado (requiere apoyo sustancial)'), ('grave', 'Grave (requiere apoyo muy sustancial)')], default='ausente', max_length=20, verbose_name='A.3 — Deficiencias en desarrollo, mantenimiento y comprensión de relaciones'),
        ),
        migrations.AddField(
            model_name='evaluaciondsm5',
            name='puntaje_total_a',
            field=models.IntegerField(default=0, editable=False, verbose_name='Puntaje Total Criterio A'),
        ),
        migrations.AlterField(
            model_name='evaluaciondsm5',
            name='nivel_comunicacion_social',
            field=models.CharField(choices=[('necesita_apoyo', 'Nivel 1 — Necesita apoyo'), ('apoyo_sustancial', 'Nivel 2 — Apoyo sustancial'), ('apoyo_constante', 'Nivel 3 — Necesita apoyo constante')], max_length=30, verbose_name='Nivel general de comunicación social (Criterio A)'),
        ),
    ]
