# Generated by Django 6.0.5 on 2026-05-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experto', '0012_remove_evaluaciondsm5_obs_comunicacion_no_verbal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciondsm5',
            name='asociado_trastorno_neurodesarrollo',
            field=models.BooleanField(default=False, verbose_name='Asociado a otro trastorno del neurodesarrollo, mental o del comportamiento'),
        ),
        migrations.AddField(
            model_name='evaluaciondsm5',
            name='con_catatonia',
            field=models.BooleanField(default=False, verbose_name='Con catatonía'),
        ),
        migrations.AddField(
            model_name='evaluaciondsm5',
            name='perdida_habilidades',
            field=models.BooleanField(default=False, verbose_name='Pérdida de habilidades previamente adquiridas'),
        ),
        migrations.AlterField(
            model_name='evaluaciondsm5',
            name='a1_reciprocidad',
            field=models.BooleanField(default=False, verbose_name='A.1 — Deficiencias en la reciprocidad socioemocional'),
        ),
        migrations.AlterField(
            model_name='evaluaciondsm5',
            name='a2_comunicacion_no_verbal',
            field=models.BooleanField(default=False, verbose_name='A.2 — Deficiencias en conductas comunicativas no verbales'),
        ),
        migrations.AlterField(
            model_name='evaluaciondsm5',
            name='a3_relaciones',
            field=models.BooleanField(default=False, verbose_name='A.3 — Deficiencias en desarrollo, mantenimiento y comprensión de relaciones'),
        ),
    ]
